"""Initial migration

Revision ID: 5f5fb82d0d66
Revises: 
Create Date: 2026-01-02 14:19:23.120184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f5fb82d0d66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('daily_word_limit', sa.Integer(), nullable=False),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_time', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('words_reviewed', sa.Integer(), nullable=False),
    sa.Column('words_correct', sa.Integer(), nullable=False),
    sa.Column('words_incorrect', sa.Integer(), nullable=False),
    sa.Column('new_words', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_started', 'study_sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('translation', sa.String(length=500), nullable=True),
    sa.Column('added_by', sa.BigInteger(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', name='uq_word_lowercase')
    )
    op.create_index('idx_word_lower', 'words', ['word'], unique=False)
    op.create_index(op.f('ix_words_word'), 'words', ['word'], unique=False)
    op.create_table('user_word_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('leitner_box', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=True),
    sa.Column('times_reviewed', sa.Integer(), nullable=False),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('times_incorrect', sa.Integer(), nullable=False),
    sa.Column('next_review_date', sa.Date(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_word')
    )
    op.create_index('idx_leitner_box', 'user_word_progress', ['leitner_box'], unique=False)
    op.create_index('idx_user_next_review', 'user_word_progress', ['user_id', 'next_review_date'], unique=False)
    op.create_table('word_edit_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('edited_by', sa.BigInteger(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_edited', 'word_edit_history', ['edited_by', 'edited_at'], unique=False)
    op.create_index('idx_word_edited', 'word_edit_history', ['word_id', 'edited_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_word_edited', table_name='word_edit_history')
    op.drop_index('idx_user_edited', table_name='word_edit_history')
    op.drop_table('word_edit_history')
    op.drop_index('idx_user_next_review', table_name='user_word_progress')
    op.drop_index('idx_leitner_box', table_name='user_word_progress')
    op.drop_table('user_word_progress')
    op.drop_index(op.f('ix_words_word'), table_name='words')
    op.drop_index('idx_word_lower', table_name='words')
    op.drop_table('words')
    op.drop_index('idx_user_started', table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
